### ISSUE TITLE
comment on build

### ISSUE THREAD

**Issue by Lenochxd** [anna8abrus/pourquoisiserieux#1]
cc comment on build
pourquoi si sérieux???????

![banner](https://github.com/user-attachments/assets/b826e6db-e5a4-4553-9e6b-dfdef8934555)

**Comment by utade** [comment]
faut avoir gcc et apres tu fait
`g++ main.cpp -o main`

**Comment by Lenochxd** [comment]
oui j'ai une gcc une gamecube controller mais je vois pas le rapport avec le code là

**Comment by utade** [comment]
mais non pas gamecube controller

ça https://github.com/brechtsanders/winlibs_mingw/releases/download/14.2.0posix-19.1.1-12.0.0-ucrt-r2/winlibs-x86_64-posix-seh-gcc-14.2.0-mingw-w64ucrt-12.0.0-r2.7z
